- hosts: localhost
  remote_user: 
  become: yes
  become_method: sudo
  tasks:
  - name: Repo update
    apt: update_cache=yes

  - name: Instalar dependencias
    apt: name={{ item }}
    with_items:
      - git
      - python-setuptools
      - python-dev
      - build-essential
      - python-psycopg2

  - name: Instalar pip
    easy_install: name=pip
