# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encolado',
            old_name='nick',
            new_name='nick_encolado',
        ),
    ]
