# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0002_auto_20161011_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nick',
            new_name='nick_usuario',
        ),
        migrations.AddField(
            model_name='cola',
            name='nombre_cola',
            field=models.CharField(default='', max_length=20),
        ),
    ]
