# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0003_auto_20161014_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
