# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0004_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cola',
            name='nombre_cola',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='encolado',
            name='codigo_cola',
            field=models.CharField(max_length=8),
        ),
    ]
